### ISSUE TITLE
Questions about scatterRead

### ISSUE THREAD

**Issue by 1ness** [imerzan/VmmFrost#2]
Hi，Can you provide a complete example of reading a list of entities.
I actually never figured out how to read all the entity pointer information at once via scatterRead, since I have a long pointer chain for each entity (I think I have to go through a nested parsing process to get the final pointer content?)

**Comment by imerzan** [comment]
> Hi，Can you provide a complete example of reading a list of entities.
> 
> I actually never figured out how to read all the entity pointer information at once via scatterRead, since I have a long pointer chain for each entity (I think I have to go through a nested parsing process to get the final pointer content?)

There is an example in the reader
