### ISSUE TITLE
maximum performance of scatterRead

### ISSUE THREAD

**Issue by 1ness** [imerzan/VmmFrost#4]
Can you please tell me how much is the maximum performance of scatterRead?I tested the following code and found that count>900 will result in <60 FPS per esp loop. Is there any way to break through this ceiling?

int counts = 800;
var Map = new ScatterReadMap(counts);
var Round1 = Map.AddRound(true);
for (int i= 0; i< counts; i++) 
{
     var Entity = Round1.AddEntry<MemPointer>(i, 0, OFFSET_GBase , null, (uint)(i<< 5));
}
                
entityMap.Execute(mem);

**Comment by imerzan** [comment]
Likely not an issue with this codebase, I get ~600 fps on my ESP with it.
